development:
  adapter: postgresql
  encoding: unicode
  database: stats_com_dev
  pool: 5
  username: postgres
  password: suite101

test:
  adapter: postgresql
  encoding: unicode
  database: stats_com_test
  pool: 5
  username: postgres
  password: suite101

production:
  adapter: postgresql
  encoding: unicode
  database: stats_production
  pool: 5
  username: postgres
  password: suite101
